### ISSUE TITLE
试了一下，非常不准

### ISSUE THREAD

**Issue by daidi** [pengzhendong/pyannote-onnx#2]
是不支持中文还是？
找了个podcast的两人访谈分了一下，结果虽然分出来了，但是完全没逻辑，感觉是乱分的，囧rz

**Comment by pengzhendong** [comment]
方便提供下音频吗？

**Comment by pengzhendong** [comment]
这个模型最多只支持三个说话人

**Comment by daidi** [comment]
你好，试试这个
https://jt.ximalaya.com//GKwRIJEIbhnkAT3DHgIuwteU-aacv2-48K.m4a?channel=rss&amp;album_id=74194808&amp;track_id=643993272&amp;uid=28103699&amp;jt=https://audio.xmcdn.com/storages/7970-audiofreehighqps/07/AC/GKwRIJEIbhnkAT3DHgIuwteU-aacv2-48K.m4a

**Comment by leohuang2013** [comment]
> 这个模型最多只支持三个说话人

我看pyannote.audio可以超过三个。

**Comment by pengzhendong** [comment]
> 你好，试试这个 https://jt.ximalaya.com//GKwRIJEIbhnkAT3DHgIuwteU-aacv2-48K.m4a?channel=rss&amp;album_id=74194808&amp;track_id=643993272&amp;uid=28103699&amp;jt=https://audio.xmcdn.com/storages/7970-audiofreehighqps/07/AC/GKwRIJEIbhnkAT3DHgIuwteU-aacv2-48K.m4a

这个需要提取单声道音频，转 16k 采样率，然后分段识别，再用 embedding 聚类

**Comment by pengzhendong** [comment]
> > 这个模型最多只支持三个说话人
> 
> pyannote.audio可以超过三个。我使用他们的示例代码测试我上面的文件，结果挺准确的。

那就是需要加上后续的分割聚类，这里只转了 pyannote-segment 这个模型。

**Comment by daidi** [comment]
> > 你好，试试这个 https://jt.ximalaya.com//GKwRIJEIbhnkAT3DHgIuwteU-aacv2-48K.m4a?channel=rss&amp;album_id=74194808&amp;track_id=643993272&amp;uid=28103699&amp;jt=https://audio.xmcdn.com/storages/7970-audiofreehighqps/07/AC/GKwRIJEIbhnkAT3DHgIuwteU-aacv2-48K.m4a
> 
> 这个需要提取单声道音频，转 16k 采样率，然后分段识别，再用 embedding 聚类

没太看懂，我用ffmpeg转16k了，然后直接用这个模型，可以不？怎么理解“分段识别，再用 embedding 聚类”，我看这个output似乎没有输出embedding

**Comment by pengzhendong** [comment]
> > > 你好，试试这个 https://jt.ximalaya.com//GKwRIJEIbhnkAT3DHgIuwteU-aacv2-48K.m4a?channel=rss&amp;album_id=74194808&amp;track_id=643993272&amp;uid=28103699&amp;jt=https://audio.xmcdn.com/storages/7970-audiofreehighqps/07/AC/GKwRIJEIbhnkAT3DHgIuwteU-aacv2-48K.m4a
> > 
> > 
> > 这个需要提取单声道音频，转 16k 采样率，然后分段识别，再用 embedding 聚类
> 
> 没太看懂，我用ffmpeg转16k了，然后直接用这个模型，可以不？怎么理解“分段识别，再用 embedding 聚类”，我看这个output似乎没有输出embedding

这里只是其中一环，想要获得更高的准确率，需要对分段的结果进行聚类和重新分段。

**Comment by daidi** [comment]
> > > > 你好，试试这个 https://jt.ximalaya.com//GKwRIJEIbhnkAT3DHgIuwteU-aacv2-48K.m4a?channel=rss&amp;album_id=74194808&amp;track_id=643993272&amp;uid=28103699&amp;jt=https://audio.xmcdn.com/storages/7970-audiofreehighqps/07/AC/GKwRIJEIbhnkAT3DHgIuwteU-aacv2-48K.m4a
> > > 
> > > 
> > > 这个需要提取单声道音频，转 16k 采样率，然后分段识别，再用 embedding 聚类
> > 
> > 
> > 没太看懂，我用ffmpeg转16k了，然后直接用这个模型，可以不？怎么理解“分段识别，再用 embedding 聚类”，我看这个output似乎没有输出embedding
> 
> 这里只是其中一环，想要获得更高的准确率，需要对分段的结果进行聚类和重新分段。

请问有合适的开源方案推荐吗？可以在本地电脑cpu推理的

**Comment by pengzhendong** [comment]
可以尝试使用 pyannote-audio 官方的 pipeline

**Comment by leohuang2013** [comment]
> > > 这个模型最多只支持三个说话人
> > 
> > 
> > pyannote.audio可以超过三个。我使用他们的示例代码测试我上面的文件，结果挺准确的。
> 
> 那就是需要加上后续的分割聚类，这里只转了 pyannote-segment 这个模型。

我在想直接使用speechbrain的spkrec-ecapa-voxceleb
https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb
得到帧级别embeddings，然后使用k-means聚类，就可以做到speaker diarization了。这样就没有用到segmentation，是不是有问题？

**Comment by pengzhendong** [comment]
一帧记不了多少声纹的信息，通常的做法是先用 vad 分段，然后默认每段只有一个人再说话，再算 embedding 去聚类。

**Comment by leohuang2013** [comment]
> 一帧记不了多少声纹的信息，通常的做法是先用 vad 分段，然后默认每段只有一个人再说话，再算 embedding 去聚类。

按照你的提示，我把pyannote的speaker diarization的整个pipeline翻译成了c++，
https://github.com/leohuang2013/pyannote-audio_speaker-diarization_cpp
