### ISSUE TITLE
关于转onnx模型后模型大小和精度发生变化

### ISSUE THREAD

**Issue by axuan731** [pengzhendong/pyannote-onnx#3]
您好，根据您提供的代码我训练了一个VAD.ckpt(8.2M)后转成ONNX模型变成了2.8M
用音频测试的时候错误率和ckpt相比变高了一些
想问一下这是怎么造成的，有没有好的解决思路
感谢

**Comment by pengzhendong** [comment]
你是不是用了量化？

**Comment by axuan731** [comment]
> 你是不是用了量化？

没有，我只在源代码的基础上加了opset=12

**Comment by pengzhendong** [comment]
方便的话发一下模型看看

**Comment by axuan731** [comment]
> 方便的话发一下模型看看

[VAD.zip](https://github.com/pengzhendong/pyannote-onnx/files/12450357/VAD.zip)
ckpt和onnx模型都已附上，感谢
