### ISSUE TITLE
pyannote_onnx.py#L98

### ISSUE THREAD

**Issue by axuan731** [pengzhendong/pyannote-onnx#6]
Dear pengzhendong,
    Thank you for sharing your code. In the file pyannote_onnx.py, specifically at [this line](https://github.com/pengzhendong/pyannote-onnx/blob/master/pyannote_onnx/pyannote_onnx.py#L98), I believe there might be an issue with how step is calculated. 
     I suggest modifying it to:
     step = max(min(step, 0.9 * self.duration), self.duration // 2)
Best regards！^_^

**Comment by pengzhendong** [comment]
You are right. Thanks, could you make a pull request?
